config/routes.rb
require_relative "../app/constraints/panda/cms/admin_constraint"

Panda::CMS::Engine.routes.draw do
  constraints Panda::CMS::AdminConstraint.new(&:present?) do
    namespace Panda::CMS.route_namespace, as: :admin, module: :admin do
      resources :files
      resources :forms, only: %i[index show]
      resources :menus
      resources :pages do
        resources :block_contents, only: %i[update]
      end
      resources :posts

      get "settings", to: "settings#index"
      namespace :settings, as: :settings do
        get "bulk_editor", to: "bulk_editor#new"
        post "bulk_editor", to: "bulk_editor#create"
      end

      if Rails.env.development?
        mount Lookbook::Engine, at: "/lookbook"
      end
    end

    get Panda::CMS.route_namespace, to: "admin/dashboard#show", as: :admin_dashboard
  end

  ### PUBLIC ROUTES ###

  # Authentication routes
  get Panda::CMS.route_namespace, to: "admin/sessions#new", as: :admin_login
  # Get and post options here are for OmniAuth coming back in, not going out
  match "#{Panda::CMS.route_namespace}/auth/:provider/callback", to: "admin/sessions#create", as: :admin_login_callback, via: %i[get post]
  match "#{Panda::CMS.route_namespace}/auth/failure", to: "admin/sessions#failure", as: :admin_login_failure, via: %i[get post]
  # OmniAuth additionally adds a GET route for "#{Panda::CMS.route_namespace}/auth/:provider" but doesn't name it
  delete Panda::CMS.route_namespace, to: "admin/sessions#destroy", as: :admin_logout

  if Panda::CMS.config.posts[:enabled]
    # TODO: Allow multiple types of post in future
    # TODO: This now requires a page to be created, make it explicit (with a rendering posts helper?)
    # get Panda::CMS.posts[:prefix], to: "posts#index", as: :posts
    get "#{Panda::CMS.config.posts[:prefix]}/:slug", to: "posts#show", as: :post
  end

  ### APPENDED ROUTES ###

  # See lib/panda/cms/engine.rb
end

app/controllers/panda/cms/admin/forms_controller.rb
# frozen_string_literal: true

module Panda
  module CMS
    module Admin
      class FormsController < ApplicationController
        before_action :set_initial_breadcrumb, only: %i[index show]
        # before_action :set_paper_trail_whodunnit, only: %i[create update]
        before_action :authenticate_admin_user!

        # Lists all forms
        # @type GET
        # @return ActiveRecord::Collection A list of all forms
        def index
          forms = Panda::CMS::Form.order(:name)
          render :index, locals: {forms: forms}
        end

        def show
          form = Panda::CMS::Form.find(params[:id])

          add_breadcrumb form.name, admin_form_path(form)
          submissions = form.form_submissions.order(created_at: :desc)
          # TODO: Set a whitelist of fields we allow to be submitted for the form, shown in this view
          # and a formatting array of how to display them... eventually?

          fields = if submissions.last
            submissions.last.data.keys.reverse.map { |field| [field, field.titleize] }
          else
            []
          end

          render :show, locals: {form: form, submissions: submissions, fields: fields}
        end

        private

        def set_initial_breadcrumb
          add_breadcrumb "Forms", admin_forms_path
        end

        private

        # Only allow a list of trusted parameters through
        # @type private
        # @return ActionController::StrongParameters
        def form_params
          params.require(:form).permit(:name, :completion_path)
        end
      end
    end
  end
end

app/views/panda/cms/admin/forms/index.html.erb
<%= render Panda::CMS::Admin::ContainerComponent.new do |component| %>
  <% component.with_heading(text: "Forms", level: 1) do |heading| %>
  <% end %>

  <%= render Panda::CMS::Admin::TableComponent.new(term: "form", rows: forms) do |table| %>
    <% table.column("Name") { |form| block_link_to form.name, admin_form_path(form) } %>
    <% table.column("Status") { |form| render Panda::CMS::Admin::TagComponent.new(status: :active) } %>
    <% table.column("Last Submission") do |form| %>
      <%= "#{time_ago_in_words(form.form_submissions&.last&.created_at)} ago" if form.form_submissions&.last %>
    <% end %>
    <% table.column("Completion Path", &:completion_path) %>
  <% end %>
<% end %>

app/views/panda/cms/admin/forms/new.html.erb
<%= render Panda::CMS::Admin::ContainerComponent.new do |component| %>
  <% component.with_heading(text: "Add Page", level: 1) do |heading| %>
  <% end %>
  <%= panda_cms_form_with model: page, url: admin_pages_path, method: :post do |f| %>
    <% options = nested_set_options(Panda::CMS::Page, page) { |i| "#{"-" * i.level} #{i.title} (#{i.path})" } %>
    <div data-controller="slug">
      <input type="hidden" value="<%= Panda::CMS::Current.root %>" data-slug-target="existing_root">
      <%= f.select :parent_id, options, {}, { "data-slug-target": "input_select", "data-action": "change->slug#setPrePath" } %>
      <%= f.text_field :title, { data: { "slug-target": "input_text", action: "focusout->slug#generatePath" } } %>
      <%= f.text_field :path, { data: { prefix: Panda::CMS::Current.root, "slug-target": "output_text" } } %>
      <%= f.collection_select :panda_cms_template_id, Panda::CMS::Template.available, :id, :name %>
      <%= f.button %>
    </div>
  <% end %>
<% end %>

app/views/panda/cms/admin/forms/show.html.erb
<%= render Panda::CMS::Admin::ContainerComponent.new do |component| %>
  <% component.with_heading(text: form.name, level: 1) do |heading| %>
  <% end %>

  <div class="overflow-x-auto -mx-4 rounded-lg ring-1 sm:mx-0 sm:rounded-lg ring-mid">
    <table class="min-w-full divide-y divide-gray-300 border-collapse table-auto">
      <thead>
        <tr>
          <% fields.each do |field, title| %>
          <th scope="col" class="py-3.5 px-3 text-sm font-semibold text-left text-gray-900"><%= title %></th>
          <% end %>
          <th scope="col" class="py-3.5 px-3 text-sm font-semibold text-left text-gray-900">Submitted</th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        <% submissions.each do |submission| %>
        <tr class="relative bg-white cursor-pointer hover:bg-gray-50">
          <% fields.each do |field| %>
          <td class="py-5 px-3 text-sm text-gray-500">
            <% if field[0] == "email" || field[0] == "email_address" %>
              <a href="mailto:<%= submission.data[field[0]] %>" class="border-b border-gray-500 hover:text-gray-900"><%= submission.data[field[0]] %></a>
            <% else %>
              <%= simple_format(submission.data[field[0]]) %>
            <% end %>
          </td>
          <% end %>
          <td class="py-5 px-3 text-sm text-gray-500 whitespace-nowrap">
            <div class="text-gray-500"><%= time_ago_in_words(submission.created_at) %> ago</div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>