config/routes.rb
require_relative "../app/constraints/panda/cms/admin_constraint"

Panda::CMS::Engine.routes.draw do
  constraints Panda::CMS::AdminConstraint.new(&:present?) do
    namespace Panda::CMS.route_namespace, as: :admin, module: :admin do
      resources :files
      resources :forms, only: %i[index show]
      resources :menus
      resources :pages do
        resources :block_contents, only: %i[update]
      end
      resources :posts

      get "settings", to: "settings#index"
      namespace :settings, as: :settings do
        get "bulk_editor", to: "bulk_editor#new"
        post "bulk_editor", to: "bulk_editor#create"
      end

      if Rails.env.development?
        mount Lookbook::Engine, at: "/lookbook"
      end
    end

    get Panda::CMS.route_namespace, to: "admin/dashboard#show", as: :admin_dashboard
  end

  ### PUBLIC ROUTES ###

  # Authentication routes
  get Panda::CMS.route_namespace, to: "admin/sessions#new", as: :admin_login
  # Get and post options here are for OmniAuth coming back in, not going out
  match "#{Panda::CMS.route_namespace}/auth/:provider/callback", to: "admin/sessions#create", as: :admin_login_callback, via: %i[get post]
  match "#{Panda::CMS.route_namespace}/auth/failure", to: "admin/sessions#failure", as: :admin_login_failure, via: %i[get post]
  # OmniAuth additionally adds a GET route for "#{Panda::CMS.route_namespace}/auth/:provider" but doesn't name it
  delete Panda::CMS.route_namespace, to: "admin/sessions#destroy", as: :admin_logout

  if Panda::CMS.config.posts[:enabled]
    # TODO: Allow multiple types of post in future
    # TODO: This now requires a page to be created, make it explicit (with a rendering posts helper?)
    # get Panda::CMS.posts[:prefix], to: "posts#index", as: :posts
    get "#{Panda::CMS.config.posts[:prefix]}/:slug", to: "posts#show", as: :post
  end

  ### APPENDED ROUTES ###

  # See lib/panda/cms/engine.rb
end

app/views/panda/cms/admin/shared/_breadcrumbs.html.erb
<% breadcrumb_styles = "text-black/60 hover:text-black/80" %>

<div class="flex mt-1 -mb-1">
  <nav aria-label="Breadcrumb" id="panda-breadcrumbs" class="grow">
    <ol role="list" class="px-4 w-full sm:px-6">
      <li class="inline-block">
        <a href="/admin" class="<%= breadcrumb_styles %>">
          <i class="fa fa-regular fa-house"></i>
          <span class="sr-only">Home</span>
        </a>
      </li>
      <% breadcrumbs.each do |crumb| %>
        <li class="inline-block">
          <i class="fa fa-regular fa-chevron-right font-light <%= breadcrumb_styles %> py-5 px-2"></i>
          <a href="<%= crumb.path %>" class="text-sm font-normal <%= breadcrumb_styles %>"><%= crumb.name %></a>
        </li>
      <% end %>
    </ol>
  </nav>

  <% if content_for :sidebar %>
    <div class="pt-4 pr-8 text-black/80" tabindex="-1">
      <a href="#" id="slideover-toggle" data-action="click->toggle#toggle touch->toggle#toggle" class="text-sm font-light">
        <i class="mr-1 fa-light fa-gear"></i> <%= yield :sidebar_title %>
      </a>
    </div>
  <% end %>
</div>

app/views/panda/cms/admin/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |kind, message| %>
    <%= render Panda::CMS::Admin::FlashMessageComponent.new(kind: kind, message: message) %>
  <% end %>
<% end %>

app/views/panda/cms/admin/shared/_sidebar.html.erb
<nav class="flex flex-col flex-1">
  <ul role="list" class="flex flex-col flex-1">
    <a class="block p-0 mt-4 mb-4 ml-2 text-xl font-medium text-white"><%= Panda::CMS.config.title %></a>
    <% [
      { path: admin_dashboard_path, text: "Dashboard", icon: "fa-house", matcher: :exact },
      { path: admin_pages_path, text: "Pages", icon: "fa-page", matcher: :starts_with },
      { path: admin_posts_path, text: "Posts", icon: "fa-notebook", matcher: :starts_with },
      { path: admin_forms_path, text: "Forms", icon: "fa-cabinet-filing", matcher: :starts_with },
      { path: admin_menus_path, text: "Menus", icon: "fa-list-dropdown", matcher: :starts_with },
      { path: admin_settings_path, text: "Settings", icon: "fa-cog", matcher: :starts_with },
    ].each do |link| %>
      <li>
        <%= link_to link[:path], class: "#{active_link?(link[:path], match: link[:matcher]) ? selected_nav_highlight_colour_classes(request) : nav_highlight_colour_classes(request)}" do %>
          <span class="text-center"><i class="fa-regular <%= link[:icon] %> text-xl fa-fw"></i></span>
          <span class="mt-1"><%= link[:text] %></span>
        <% end %>
      </li>
    <% end %>
    <li>
      <%= button_to admin_logout_path, method: :delete, id: "logout-link", data: { turbo: false }, class: nav_highlight_colour_classes(request) + " w-full" do %>
        <span class="text-center"><i class="text-xl fa-regular fa-door-open fa-fw"></i></span>
        <span class="mt-1">Logout</span>
      <% end %>
    </li>
    <li class="mt-auto">
      <%= button_to '#', data: { turbo: false }, class: nav_highlight_colour_classes(request) + " w-full" do %>
        <% if !current_user.image_url.to_s.empty? %>
          <span class="text-center"><img src="<%= current_user.image_url %>" class="w-auto h-7 rounded-full"></span>
        <% else %>
          <span class="text-center"><i class="text-xl fa-regular fa-circle-user fa-fw"></i></span>
        <% end %>
        <span class="mt-0.5"><%= current_user.firstname %> <%= current_user.lastname %></span>
      <% end %>
    </li>
    <li class="">
      <img src="/panda-cms-assets/panda-nav.png" class="inline py-2 mr-1 ml-0.5 w-auto h-14">
      <span class="text-xs text-white">v<%= Panda::CMS::VERSION %> | <span class="font-semibold">License:</span> Perpetual</span>
      <a class="absolute right-0 mt-4 mr-5 text-lg text-white lg:hidden" href="#" data-action="click->panda-cms-menu#toggle touch->panda-cms-menu#toggle"><i class="mr-2 text-white fa-sharp fa-solid fa-bars"></i> Menu</a>
    </li>
  </ul>
</nav>